config/routes.rb
The86Sample::Application.routes.draw do

  root to: redirect("/sites")

  resources :sites,
    only: [:index, :show] do

    resources :conversations,
      only: [:create] do

      resources :posts,
        only: [:create] do

        post :hide

      end

    end

  end

  match "sign-in", to: "authentication#sign_in", as: :sign_in
  match "sign-out", to: "authentication#sign_out", as: :sign_out

end

app/models/user.rb
class User

  class << self

    attr_writer :session

    def find(id)
      where(id: id).first || raise("User #{id} not found")
    end

    def where(attributes)
      session_users.select do |user|
        attributes.keys.all? do |key|
          user.send(key) == attributes[key]
        end
      end
    end

    def create(attributes)
      self.new(attributes.merge(id: next_id)).tap do |u|
        session_users << u
      end
    end

    private

    def next_id
      (session_users.map(&:id).max || 0) + 1
    end

    def session
      @session || raise("User has no reference to session")
    end

    def session_users
      session[:users] ||= []
    end

  end

  def initialize(attributes)
    attributes.each { |key, value| send("#{key}=", value) }
  end

  attr_accessor :id, :name
  attr_accessor :oauth_token

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  include AuthenticationHelper

  protect_from_forgery

end

app/controllers/authentication_controller.rb
class AuthenticationController < ApplicationController

  def sign_in
    authenticator.sign_in(user_from_url)
    redirect_to root_url
  end

  def sign_out
    authenticator.sign_out
    redirect_to root_url
  end

  private

  def user_from_url
    name = params[:name]
    user_class.where(name: name).first || create_user(name)
  end

  def user_class
    User.tap { |u| u.session = session }
  end

  def create_user(name)
    remote = The86::Client.users.create(name: name)
    user_class.create(name: name, oauth_token: remote.access_tokens.first.token)
  end

end

app/controllers/conversations_controller.rb
class ConversationsController < ApplicationController

  def create
    conversation = site.conversations.build(
      params.require(:post).permit(:content).merge(
        oauth_token: current_user.oauth_token,
      )
    )
    conversation.save
    redirect_to site_url(site.slug)
  rescue The86::Client::ValidationFailed => e
    # TODO: display validation errors
    # render "sites/show"
    redirect_to site_url(site.slug)
  end

  private

  # The Site from the URL.
  def site
    @site ||= The86::Client.site(params[:site_id])
  end

end

app/controllers/posts_controller.rb
require "site_presenter"

class PostsController < ApplicationController

  def create
    post = conversation.posts.build(
      params.require(:post).permit(:content, :in_reply_to_id).merge(
        oauth_token: current_user.oauth_token,
      )
    )
    post.save
    redirect_to site_url(site)
  rescue The86::Client::ValidationFailed => e
    # TODO: show validation errors
    # render_error(post)
    redirect_to site_url(site)
  end

  def hide
    if params[:hide_type] == "user"
      post.hide(oauth_token: current_user.oauth_token)
    else
      post.hide
    end
    redirect_to site_url(site)
  end

  private

  def render_error(post)
    @presenter = SitePresenter.new(site)
    if in_reply_to
      @presenter.set_new_reply_to(in_reply_to, post)
    elsif conversation
      @presenter.set_new_follow_up(conversation, post)
    else
      @presenter.set_new_post(post)
    end
    render "sites/show"
  end

  def post
    @_post ||= conversation.posts.build(id: params[:post_id] || params[:id])
  end

  # Conversation for the posted ID, or nil.
  def conversation
    @_conversation ||=
      site.conversations.build(id: params[:conversation_id] || params[:id])
  end

  # The Site from the URL.
  def site
    @site ||= The86::Client.site(params[:site_id])
  end

end

app/controllers/sites_controller.rb
class SitesController < ApplicationController

  def index
    @sites = The86::Client.sites
  end

  def show
    @presenter = SitePresenter.new(site)
  end

  private

  def site
    @_site ||= The86::Client.site(params[:site_id] || params[:id]).load
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/authentication_helper.rb
require "authenticator"

module AuthenticationHelper

  def authentication_path(provider)
    "/auth/#{provider}"
  end

  def current_user?
    authenticator.current_user?
  end

  def current_user
    authenticator.current_user
  end

  private

  def authenticator
    @authenticator ||= Authenticator.new(session).tap do |auth|
      auth.user_finder = User.tap{ |k| k.session = session }.method(:find)
    end
  end

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>The86 Sample</title>
  <%= csrf_meta_tags %>
</head>
<body>

<% if current_user? %>
  <p>Welcome, <%= current_user.name %>.</p>
<% end %>

<%= yield %>

</body>
</html>

app/views/sites/_conversation.html.haml
%hr
.conversation

  %ul.conversation
    - conversation.posts.each do |post|
      %li
        = render partial: "post", locals: { post: post,
          conversation: conversation,
          site_presenter: @presenter }

  .follow-up
    = render partial: "sites/follow_up_form", locals: { site: @presenter.site,
              conversation: conversation,
              new_post: @presenter.new_follow_up(conversation) }

app/views/sites/_follow_up_form.html.haml
%p Post follow-up

= simple_form_for(new_post, url: site_conversation_posts_path(site.slug, conversation.id), namespace: "conversation_#{conversation.id}") do |f|
  = render partial: "/form_errors", locals: { record: new_post }
  = f.input :content, label: "Follow up", as: :text, input_html: { size: "80x2" }
  = f.input :conversation_id, as: :hidden, input_html: { value: conversation.id }
  = f.button :submit, value: "Follow up"

app/views/sites/_new_conversation.html.haml
%p Post update

= simple_form_for(post, url: site_conversations_path(site.slug) ) do |f|
  = render partial: "/form_errors", locals: { record: post }
  = f.input :content, label: "Post update", as: :text, input_html: { size: "80x4" }
  = f.button :submit, value: "Post"

app/views/sites/_post.html.haml
- if post.reply?
  %p
    = "#{post.user.name}, in reply to #{post.in_reply_to.user.name}, says:"
- else
  %p
    = post.user.name
    says:

%p= post.content

= form_tag site_conversation_post_hide_path(site_presenter.site.slug, conversation.id, post.id), method: :post do
  = hidden_field_tag :hide_type, "admin"
  = submit_tag "Hide (Admin)"

- if current_user?
  = form_tag site_conversation_post_hide_path(site_presenter.site.slug, conversation.id, post.id), method: :post do
    = hidden_field_tag :hide_type, "user"
    = submit_tag "Hide (User)"

  = render partial: "sites/reply_form", locals: { site: site_presenter.site,
      conversation: conversation,
      in_reply_to: post,
      new_post: site_presenter.new_reply_to(post) }

app/views/sites/_reply_form.html.haml
%p Post reply

= simple_form_for(new_post, url: site_conversation_posts_path(site.slug, conversation.id), namespace: "in_reply_to_post_#{in_reply_to.id}") do |f|
  = render partial: "/form_errors", locals: { record: new_post }
  = f.input :content, label: "Post reply", as: :text, input_html: { size: "80x2" }
  = f.input :in_reply_to_id, as: :hidden, input_html: { value: in_reply_to.id }
  = f.button :submit, value: "Reply"

app/views/sites/index.html.haml
%h1 Sites

%ul
  - @sites.each do |site|
    %li= link_to site.name, site_path(site.slug)

app/views/sites/show.html.haml
%h1= @presenter.site.name

- if current_user?
  = render partial: "sites/new_conversation",
      locals: { site: @presenter.site, post: @presenter.new_post }

- if @presenter.site.conversations.any?
  %ul
  - @presenter.site.conversations.each do |c|
    %li
      = render partial: "sites/conversation", locals: { conversation: c }
- else
  %p No conversations yet